name: Build macOS App
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          brew install python3
          pip3 install pyinstaller
      - name: Build App
        run: pyinstaller --onefile --windowed your_script.py
      - name: Upload Build
        uses: actions/upload-artifact@v2 # Use version 2 for upload artifact (known to be stable)
        with:
          name: mac-app
          path: dist/
